---
- name: Test ovirt_snapshot
  hosts: ovirt36
  remote_user: centos
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: Create Ovirt snapshot
    ovirt_snapshot:
     state: present
     url: https://127.0.0.1
     user: admin@internal
     password: unix1234
     name: "{{ item }}"
     wait: True
     vm: prout1
     force: True
    with_items:
     - X1
     - X2
     - X3
