---
- name: Test this stuff
  hosts: ovirt36
  remote_user: centos
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: Remove Specific Ovirt snapshot 
    ovirt_snapshot:
     state: absent
     url: https://127.0.0.1
     user: admin@internal
     password: unix1234
     name: X1
     vm: prout1
